# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - controle-de-medicamentos-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      # Build da Aplicação .NET
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Build do Database Project SQL Server
      - name: Build database project
        run: dotnet build ControleDeMedicamentosWeb.Database/ControleDeMedicamentosWeb.Database.sqlproj --configuration Release

      # Publish da Aplicação .NET
      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      # Upload da aplicação .NET compilada
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      # Upload dos artefatos do banco de dados
      - name: Upload database artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: database-dacpac
          path: ControleDeMedicamentosWeb.Database/bin/Release/ControleDeMedicamentosWeb.Database.dacpac

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      # Download do artefato compilado .NET
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Download do artefato compilado do database project
      - name: Download database artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: database-dacpac
          path: database

      # Login do repositório na Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACC27C8186A9449C973E2066F378C61C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C92E88B920CC48B292B1E5570CDBDBCF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BADE6A77B9644888D69C434F2D47681 }}

      # Publicação do artefato do database project
      - name: Deploy database schema
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: database/ControleDeMedicamentosWeb.Database.dacpac
          action: Publish
          arguments: /p:BlockOnPossibleDataLoss=true

      # Publicação do artefato .NET na Azure
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "controle-de-medicamentos-web"
          slot-name: "Production"
          package: .
